<?php

use Drupal\file\Entity\File;
use Drupal\Core\Config;

/**
* Implements hook_preprocess_html().
*/
function itkore_base_page_attachments(array &$page) {
  //$variables['html']['#attached']['library'][] = 'itkore_base/itkore_base_styles';
  $page['#attached']['library'][] = 'itkore_base/itkore_base_styles';
}


/**
 * Implements hook_preprocess_page()
 *
 * @param $variables
 *
 */
function itkore_base_preprocess_page(&$variables) {
  // Fetch frontpage config settings.
  $config = \Drupal::getContainer()->get('itkore_base.itkore_config');

  // Frontpage variables for page template.
  if (isset($config) && $variables['is_front'] == TRUE) {
    // Fetch header top file.
    $top_image_id = $config->get('itkore_frontpage.frontpage_image');
    $file = ($top_image_id) ? File::load($top_image_id) : FALSE;
    // Set variables
    $variables['front_title'] = $config->get('itkore_frontpage.frontpage_title');
    $variables['front_lead'] = $config->get('itkore_frontpage.frontpage_lead');
    $variables['front_sub'] = $config->get('itkore_frontpage.frontpage_sub');
    $variables['front_button_text'] = $config->get('itkore_frontpage.frontpage_button');
    $variables['front_button_link'] = $config->get('itkore_frontpage.frontpage_link');
    $variables['front_image'] = ($file) ? $file->url() : 'sites/all/themes/itkore/images/header-background.jpg';
  }

  // Footer variables for page template.
  if (isset($config)) {
    $variables['footer_text'] = check_markup($config->get('itkore_footer.footer_text'), 'filtered_html');
    $variables['footer_twitter'] = $config->get('itkore_footer.footer_twitter');
    $variables['footer_instagram'] = $config->get('itkore_footer.footer_instagram');
    $variables['footer_linkedin'] = $config->get('itkore_footer.footer_linkedin');
  }
}
