<?php
/**
 * @file
 * This module shows a message on cookies being used in the site.
 *
 * The EU Directive on Privacy and Electronic Communications.
 */

/**
 * Add cookie message to page output.
 *
 * @param array $page
 *   The page to.
 */
function itk_cookie_message_page_bottom(array &$page) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $settings = itk_cookie_message_get_settings();
  $template = <<<EOF
<div id="js-cookieterms" class="cookies">
  <div class="cookies--inner">
    <span class="cookies--text">{{ text }}.
    {% if not (read_more_url is empty or read_more_text is empty) %}
    <a href="{{ read_more_url }}">{{ read_more_text }}</a>.
    {% endif %}
    </span>
    <span class="cookies--agree">
      <span id="js-cookieterms--agree" class="cookieterms--button button">{{ accept_button_text }}</span>
    </span>
  </div>
</div>
EOF;

  $values = array(
    'text' => trim($settings['text'], ".\t\n\r\0\x0B"),
    'read_more_url' => trim($settings['read_more_url']),
    'read_more_text' => trim($settings['read_more_text'], ".\t\n\r\0\x0B"),
    'accept_button_text' => trim($settings['accept_button_text'], ".\t\n\r\0\x0B"),
  );

  $twig = \Drupal::service('twig');
  $content = $twig->renderInline($template, $values);

  $page['itk_cookie_message'] = array(
    '#markup' => $content,
    '#attached' => array(
      'library' => array(
        'itk_cookie_message/itk-cookie-message',
      ),
      'drupalSettings' => array(
        'itk_cookie_message' => array(
          'cookie_name' => trim($settings['cookie_name']),
          'cookie_lifetime' => intval($settings['cookie_lifetime']),
        ),
      ),
    ),
  );
}

/**
 * Get settings for cookie messages.
 *
 * @param \Drupal\Core\Language\LanguageInterface $language
 *   The languge to use for translations.
 *
 * @return array
 *   The (localized) settings.
 */
function itk_cookie_message_get_settings(\Drupal\Core\Language\LanguageInterface $language = NULL) {
  if ($language === NULL) {
    $language = \Drupal::languageManager()->getCurrentLanguage();
  }
  $config = \Drupal::config('itk_cookie_message.settings');
  $global_settings = $config->get();
  $localized_settings = $config->get($language->getId());

  if (!is_array($localized_settings)) {
    $localized_settings = array();
  }

  // Merge default values into global settings.
  $global_settings += array(
    'cookie_name' => 'accept_cookies',
    'cookie_lifetime' => 365 * 24 * 60 * 60,
    'template' => '',
  );

  // Merge default values into localized settings.
  $localized_settings += array(
    'text' => t('This site uses cookies', array(), array('langcode' => $language->getId())),
    'read_more_url' => '',
    'read_more_text' => t('Read more', array(), array('langcode' => $language->getId())),
    'accept_button_text' => t('Accept cookies', array(), array('langcode' => $language->getId())),
  );

  return array_merge($global_settings, $localized_settings);
}
