<?php
/**
 * @file
 * Expose itkore config variables to theme.
 */

use Drupal\file\Entity\File;
use Drupal\Core\Config;

/**
 * Implements hook_preprocess_html().
 */
function itkore_admin_page_attachments(array &$page) {
  // Attached custom CSS to the admin pages.
  $page['#attached']['library'][] = 'itkore_admin/itkore_admin_styles';
}


/**
 * Implements hook_preprocess_page().
 *
 * The variables used here comes from the "admin/site-setup" administration
 * configuration form.
 */
function itkore_admin_preprocess_page(&$variables) {
  // Fetch front page config settings.
  $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');

  // Front page variables for page template.
  if (isset($config) && $variables['is_front'] == TRUE) {
    // Set variables.
    $variables['front_title'] = $config->get('itkore_frontpage.frontpage_title');
    $variables['front_lead'] = $config->get('itkore_frontpage.frontpage_lead');
    $variables['front_sub'] = $config->get('itkore_frontpage.frontpage_sub');
    $variables['front_button_text'] = $config->get('itkore_frontpage.frontpage_button');
    $variables['front_button_link'] = $config->get('itkore_frontpage.frontpage_link');
  }

  // Footer variables for page template.
  if (isset($config)) {
    // Fetch header top file.
    $top_image_id = $config->get('itkore_frontpage.frontpage_image');
    $file = ($top_image_id) ? File::load($top_image_id) : FALSE;

    $default = '/' . drupal_get_path('module', 'itkore_admin') . '/images/header-default.jpg';
    $variables['front_image'] = $file ? $file->url() : $default;
    $variables['footer_text'] = check_markup($config->get('itkore_footer.footer_text'), 'filtered_html');
    $variables['footer_twitter'] = $config->get('itkore_footer.footer_twitter');
    $variables['footer_instagram'] = $config->get('itkore_footer.footer_instagram');
    $variables['footer_linkedin'] = $config->get('itkore_footer.footer_linkedin');
    $variables['footer_facebook'] = $config->get('itkore_footer.footer_facebook');
  }
}
