<?php

use Drupal\Core\Config;

/**
* Implements hook_preprocess_html().
*/
function itkore_font_page_attachments(array &$page) {
  $config = \drupal::config('itkore_font.settings');
  $font = $config->get('itkore_font');

  switch ($font) {
    case 'roboto':
      $page['#attached']['library'][] = 'itkore_font/itkore_font_roboto';
      break;
    case 'source_sans_pro':
      $page['#attached']['library'][] = 'itkore_font/itkore_font_source_sans_pro';
      break;
    case 'titillium_web':
      $page['#attached']['library'][] = 'itkore_font/itkore_font_titillium_web';
      break;
  }
}